### ISSUE TITLE
The example code isn't working

### ISSUE THREAD

**Issue by kaotisk-hund** [hyperboria/peers#147]
I just run the example in README.md after installing hyperboria-peers successfully.
I get the following error.
console.log(Peers.peers.NA.us.california);
                          ^

TypeError: Cannot read property 'us' of undefined
    at Object.<anonymous> (/home/kaotisk/hype-peers/new.js:12:27)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by kpcyrd** [comment]
I think the folder name was changed and this should be:
```
console.log(Peers.peers.na.us.california);
```
if this doesn't work as well, check the output of:
```
console.log(Peers.peers.na);
```

**Comment by kaotisk-hund** [comment]
Yeap, it works with small letters. Both lines work.
